### ISSUE TITLE
libnova will not build on recent versions of MacOS and Fedora

### ISSUE THREAD

**Issue by QuantumForge** [JohannesBuchner/libnova#2]
I have tried to build libnova on MacOS 13.4.1 and Fedora 36. In each case, I cannot get the source to compile and install. on Fedora I do the following steps:

cd ~/src
git clone https://github.com/JohannesBuchner/libnova.git
mkdir libnova_build
cd libnova_build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../libnova

* note that on Fedora on receive a warning (Fedora 36 is using cmake version 3.26.3): 
*CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
*  Compatibility with CMake < 2.8.12 will be removed from a future version of
*  CMake.
*
*  Update the VERSION argument <min> value or use a ...<max> suffix to tell
*  CMake that the project does not need compatibility with older versions.

cmake --build .

The process dies when trying to make ../bin/test:
[ 74%] Linking C executable ../bin/test
/usr/bin/ld: CMakeFiles/test.dir/test.c.o: in function `heliocentric_test':
test.c:(.text+0x67d): undefined reference to `ln_get_heliocentric_time_diff'
/usr/bin/ld: test.c:(.text+0x6e3): undefined reference to `ln_get_heliocentric_time_diff'
/usr/bin/ld: test.c:(.text+0x752): undefined reference to `ln_get_heliocentric_time_diff'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `atan2'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `acos'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `sin'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `atan'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `asin'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `exp'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `tan'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `cbrt'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `cos'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `pow'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `log10'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `sqrt'
/usr/bin/ld: ../lib/liblibnova.so: undefined reference to `floor'
collect2: error: ld returned 1 exit status
gmake[2]: *** [lntest/CMakeFiles/test.dir/build.make:98: bin/test] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:170: lntest/CMakeFiles/test.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

On MacOS I also get "undefined reference to `ln_get_heliocentric_time_diff'" but no issues linking libm symbols.

As an additional sidenote, I cannot get the version of libnova packaged on sourceforge to build at all on MacOS due to issues with libtool. I can get it to compile on Fedora but I must force rebuilding of autoconf stuff using:
autoreconf --force --install

**Comment by JohannesBuchner** [comment]
This is a personal copy I made years ago, the original project is at https://libnova.sourceforge.net/
